#!/usr/bin/env python3
"""
Script to generate gRPC code from proto files.
"""
import os
import sys
from pathlib import Path
import subprocess

def generate_grpc_code():
    """Generate gRPC code from proto files."""
    # Define paths
    project_root = Path(__file__).parent.parent
    proto_dir = project_root / "app" / "proto"
    output_dir = project_root / "app" / "proto" / "generated"
    
    # Create output directory if it doesn't exist
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Find all proto files
    proto_files = list(proto_dir.rglob("*.proto"))
    
    if not proto_files:
        print("No proto files found in", proto_dir)
        return False
    
    # Generate Python gRPC code
    for proto_file in proto_files:
        print(f"Generating gRPC code for {proto_file.relative_to(project_root)}")
        
        try:
            # Run protoc to generate Python code
            cmd = [
                "python", "-m", "grpc_tools.protoc",
                f"--proto_path={proto_file.parent}",
                f"--python_out={output_dir}",
                f"--grpc_python_out={output_dir}",
                f"--mypy_out={output_dir}",
                str(proto_file.name)
            ]
            
            # Add include paths for well-known types if needed
            import google.protobuf
            proto_include = os.path.join(os.path.dirname(google.__file__), '_proto')
            cmd.insert(4, f"--proto_path={proto_include}")
            
            # Execute the command
            result = subprocess.run(cmd, cwd=proto_file.parent, check=True, capture_output=True, text=True)
            
            if result.returncode != 0:
                print(f"Error generating code for {proto_file}:")
                print(result.stderr)
                return False
                
            print(f"Successfully generated code for {proto_file.name}")
            
        except subprocess.CalledProcessError as e:
            print(f"Failed to generate code for {proto_file}:")
            print(e.stderr)
            return False
        except Exception as e:
            print(f"Unexpected error generating code for {proto_file}:")
            print(str(e))
            return False
    
    # Create __init__.py files in the generated directories
    for root, dirs, _ in os.walk(output_dir):
        if "__pycache__" in root:
            continue
            
        # Create __init__.py if it doesn't exist
        init_file = os.path.join(root, "__init__.py")
        if not os.path.exists(init_file):
            with open(init_file, "w", encoding="utf-8") as f:
                f.write("# Generated by generate_grpc_code.py\n")
    
    print("\nSuccessfully generated all gRPC code!")
    print(f"Output directory: {output_dir.relative_to(project_root)}")
    return True

if __name__ == "__main__":
    sys.exit(0 if generate_grpc_code() else 1)
