"""
gRPC service implementation for the AI Copilot server.
"""
import asyncio
import json
import grpc
from concurrent import futures
from typing import Any, Dict, Optional, Generator, List

from app.services.llm_service import LLMService, LLMRequest, LLMMessage
from app.server.config import ServerConfig
import logging

class AIGrpcService:
    """gRPC service for AI Copilot."""
    
    def __init__(self, llm_service: LLMService, config: ServerConfig):
        """Initialize the gRPC service.
        
        Args:
            llm_service: Instance of LLMService
            config: Server configuration
        """
        self.llm_service = llm_service
        self.config = config
        self.server = None
        self._shutdown_event = asyncio.Event()
    
    async def start(self) -> None:
        """Start the gRPC server."""
        grpc_config = self.config.get_grpc_settings()
        max_workers = grpc_config.get("max_workers", 10)
        max_message_length = grpc_config.get("max_message_length", 100 * 1024 * 1024)  # 100MB
        
        # Create gRPC server with thread pool executor
        self.server = grpc.server(
            futures.ThreadPoolExecutor(max_workers=max_workers),
            options=[
                ('grpc.max_send_message_length', max_message_length),
                ('grpc.max_receive_message_length', max_message_length),
            ]
        )
        
        # Add service to server
        # Note: The actual gRPC service class will be generated by protoc
        # This is a placeholder for the actual implementation
        # ai_service_pb2_grpc.add_AIServiceServicer_to_server(
        #     AIServiceServicer(self.llm_service), self.server
        # )
        
        # Start the server
        port = grpc_config.get("port", 50051)
        listen_addr = f'[::]:{port}'
        self.server.add_insecure_port(listen_addr)
        self.server.start()
        logging.info(f"gRPC server started on {listen_addr}")
        
        # Wait for shutdown
        await self._shutdown_event.wait()
        
        # Graceful shutdown
        await self.stop()
    
    async def stop(self) -> None:
        """Stop the gRPC server gracefully."""
        if self.server:
            # Give existing RPCs some time to complete
            await asyncio.sleep(5)
            self.server.stop(grace=5)
            self.server = None
        self._shutdown_event.set()
    
    def __enter__(self):
        """Context manager entry."""
        return self
    
    def __exit__(self, exc_type, exc_val, exc_tb):
        """Context manager exit."""
        if self.server:
            self.server.stop(0)


class AIServiceServicer:
    """gRPC service implementation for AI Copilot."""
    
    def __init__(self, llm_service: LLMService):
        """Initialize the service with an LLM service instance."""
        self.llm_service = llm_service
    
    async def Chat(self, request: Any, context: grpc.ServicerContext) -> Any:
        """Handle chat requests.
        
        Args:
            request: The gRPC request
            context: gRPC context
            
        Returns:
            gRPC response
        """
        try:
            # Convert gRPC request to LLMRequest
            llm_request = LLMRequest(
                messages=[LLMMessage(role="user", content=request.message)],
                model=request.model or "unibase-erp",
                temperature=request.temperature,
                max_tokens=request.max_tokens
            )
            
            # Generate response
            response = await self.llm_service.generate(llm_request)
            
            # Convert to gRPC response
            return self._create_chat_response(
                content=response.content,
                conversation_id=request.conversation_id or "",
                metadata=response.metadata
            )
            
        except Exception as e:
            context.set_code(grpc.StatusCode.INTERNAL)
            context.set_details(str(e))
            return self._create_chat_response(
                content="",
                conversation_id=getattr(request, 'conversation_id', ''),
                error=str(e)
            )
    
    async def StreamChat(self, request: Any, context: grpc.ServicerContext) -> Generator[Any, None, None]:
        """Handle streaming chat requests.
        
        Args:
            request: The gRPC request
            context: gRPC context
            
        Yields:
            Streamed gRPC responses
        """
        try:
            # Convert gRPC request to LLMRequest
            llm_request = LLMRequest(
                messages=[LLMMessage(role="user", content=request.message)],
                model=request.model or "unibase-erp",
                temperature=request.temperature,
                max_tokens=request.max_tokens,
                stream=True
            )
            
            # Stream responses
            async for chunk in await self.llm_service.agenerate(llm_request):
                yield self._create_chat_response(
                    content=chunk.content,
                    conversation_id=request.conversation_id or "",
                    is_stream=True
                )
                
        except Exception as e:
            context.set_code(grpc.StatusCode.INTERNAL)
            context.set_details(str(e))
            yield self._create_chat_response(
                content="",
                conversation_id=getattr(request, 'conversation_id', ''),
                error=str(e)
            )
    
    async def HealthCheck(self, request: Any, context: grpc.ServicerContext) -> Any:
        """Handle health check requests.
        
        Args:
            request: The gRPC request
            context: gRPC context
            
        Returns:
            Health check response
        """
        try:
            # Create a health check response
            return self._create_health_response(
                status="SERVING",
                message="AI Copilot service is healthy",
                details={
                    "service": "ai_copilot",
                    "status": "SERVING"
                }
            )
        except Exception as e:
            context.set_code(grpc.StatusCode.INTERNAL)
            context.set_details(str(e))
            return self._create_health_response(
                status="NOT_SERVING",
                message=f"Service error: {str(e)}",
                error=str(e)
            )
    
    def _create_chat_response(self, content: str, conversation_id: str = "", 
                            metadata: Optional[Dict] = None, error: str = "",
                            is_stream: bool = False) -> Any:
        """Create a chat response object."""
        # This would be the actual gRPC response class generated by protoc
        # For now, we'll return a dictionary that matches the expected structure
        return {
            'content': content,
            'message_id': f"msg_{int(asyncio.get_event_loop().time())}",
            'timestamp': int(asyncio.get_event_loop().time()),
            'conversation_id': conversation_id,
            'response_type': "text",
            'metadata': json.dumps(metadata or {}),
            'error': error,
            'is_stream': is_stream
        }
    
    def _create_health_response(self, status: str, message: str, 
                              details: Optional[Dict] = None, error: str = "") -> Any:
        """Create a health check response object."""
        # This would be the actual gRPC response class generated by protoc
        return {
            'status': status,
            'message': message,
            'timestamp': int(asyncio.get_event_loop().time()),
            'version': "1.0.0",
            'details': json.dumps(details or {}),
            'error': error
        }
