# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.proto import ai_copilot_pb2 as app_dot_proto_dot_ai__copilot__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in app/proto/ai_copilot_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AICopilotStub(object):
    """AI Copilot Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Chat = channel.unary_unary(
                '/ai_copilot.AICopilot/Chat',
                request_serializer=app_dot_proto_dot_ai__copilot__pb2.ChatRequest.SerializeToString,
                response_deserializer=app_dot_proto_dot_ai__copilot__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.StreamChat = channel.unary_stream(
                '/ai_copilot.AICopilot/StreamChat',
                request_serializer=app_dot_proto_dot_ai__copilot__pb2.ChatRequest.SerializeToString,
                response_deserializer=app_dot_proto_dot_ai__copilot__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/ai_copilot.AICopilot/HealthCheck',
                request_serializer=app_dot_proto_dot_ai__copilot__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=app_dot_proto_dot_ai__copilot__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class AICopilotServicer(object):
    """AI Copilot Service definition
    """

    def Chat(self, request, context):
        """Chat endpoint for processing messages
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamChat(self, request, context):
        """Stream chat for real-time responses
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check endpoint
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AICopilotServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Chat': grpc.unary_unary_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=app_dot_proto_dot_ai__copilot__pb2.ChatRequest.FromString,
                    response_serializer=app_dot_proto_dot_ai__copilot__pb2.ChatResponse.SerializeToString,
            ),
            'StreamChat': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamChat,
                    request_deserializer=app_dot_proto_dot_ai__copilot__pb2.ChatRequest.FromString,
                    response_serializer=app_dot_proto_dot_ai__copilot__pb2.ChatResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=app_dot_proto_dot_ai__copilot__pb2.HealthCheckRequest.FromString,
                    response_serializer=app_dot_proto_dot_ai__copilot__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai_copilot.AICopilot', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai_copilot.AICopilot', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AICopilot(object):
    """AI Copilot Service definition
    """

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_copilot.AICopilot/Chat',
            app_dot_proto_dot_ai__copilot__pb2.ChatRequest.SerializeToString,
            app_dot_proto_dot_ai__copilot__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ai_copilot.AICopilot/StreamChat',
            app_dot_proto_dot_ai__copilot__pb2.ChatRequest.SerializeToString,
            app_dot_proto_dot_ai__copilot__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_copilot.AICopilot/HealthCheck',
            app_dot_proto_dot_ai__copilot__pb2.HealthCheckRequest.SerializeToString,
            app_dot_proto_dot_ai__copilot__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
