# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/proto/ai_copilot.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'app/proto/ai_copilot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x61pp/proto/ai_copilot.proto\x12\nai_copilot\"\xa5\x01\n\x0b\x43hatRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x17\n\x0f\x63onversation_id\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\x12\n\nagent_type\x18\x04 \x01(\t\x12\r\n\x05model\x18\x05 \x01(\t\x12\x13\n\x0btemperature\x18\x06 \x01(\x02\x12\x12\n\nmax_tokens\x18\x07 \x01(\x05\x12\x0f\n\x07\x63ontext\x18\x08 \x01(\t\"\xb2\x01\n\x0c\x43hatResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x17\n\x0f\x63onversation_id\x18\x02 \x01(\t\x12\x12\n\nmessage_id\x18\x03 \x01(\t\x12\x15\n\rresponse_type\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\x12\x10\n\x08metadata\x18\x06 \x01(\t\x12\r\n\x05\x65rror\x18\x07 \x01(\t\x12\x19\n\x11suggested_actions\x18\x08 \x01(\t\"(\n\x12HealthCheckRequest\x12\x12\n\ncheck_type\x18\x01 \x01(\t\"Z\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x65tails\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x32\xdf\x01\n\tAICopilot\x12;\n\x04\x43hat\x12\x17.ai_copilot.ChatRequest\x1a\x18.ai_copilot.ChatResponse\"\x00\x12\x43\n\nStreamChat\x12\x17.ai_copilot.ChatRequest\x1a\x18.ai_copilot.ChatResponse\"\x00\x30\x01\x12P\n\x0bHealthCheck\x12\x1e.ai_copilot.HealthCheckRequest\x1a\x1f.ai_copilot.HealthCheckResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.proto.ai_copilot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATREQUEST']._serialized_start=43
  _globals['_CHATREQUEST']._serialized_end=208
  _globals['_CHATRESPONSE']._serialized_start=211
  _globals['_CHATRESPONSE']._serialized_end=389
  _globals['_HEALTHCHECKREQUEST']._serialized_start=391
  _globals['_HEALTHCHECKREQUEST']._serialized_end=431
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=433
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=523
  _globals['_AICOPILOT']._serialized_start=526
  _globals['_AICOPILOT']._serialized_end=749
# @@protoc_insertion_point(module_scope)
