# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import auth_pb2 as auth__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in auth_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthServiceStub(object):
    """Auth service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Authenticate = channel.unary_unary(
                '/auth.AuthService/Authenticate',
                request_serializer=auth__pb2.AuthenticateRequest.SerializeToString,
                response_deserializer=auth__pb2.AuthenticateResponse.FromString,
                _registered_method=True)
        self.ValidateToken = channel.unary_unary(
                '/auth.AuthService/ValidateToken',
                request_serializer=auth__pb2.ValidateTokenRequest.SerializeToString,
                response_deserializer=auth__pb2.ValidateTokenResponse.FromString,
                _registered_method=True)
        self.RefreshToken = channel.unary_unary(
                '/auth.AuthService/RefreshToken',
                request_serializer=auth__pb2.RefreshTokenRequest.SerializeToString,
                response_deserializer=auth__pb2.RefreshTokenResponse.FromString,
                _registered_method=True)
        self.RevokeToken = channel.unary_unary(
                '/auth.AuthService/RevokeToken',
                request_serializer=auth__pb2.RevokeTokenRequest.SerializeToString,
                response_deserializer=auth__pb2.RevokeTokenResponse.FromString,
                _registered_method=True)
        self.GetUser = channel.unary_unary(
                '/auth.AuthService/GetUser',
                request_serializer=auth__pb2.GetUserRequest.SerializeToString,
                response_deserializer=auth__pb2.GetUserResponse.FromString,
                _registered_method=True)
        self.ListUsers = channel.unary_unary(
                '/auth.AuthService/ListUsers',
                request_serializer=auth__pb2.ListUsersRequest.SerializeToString,
                response_deserializer=auth__pb2.ListUsersResponse.FromString,
                _registered_method=True)
        self.CreateUser = channel.unary_unary(
                '/auth.AuthService/CreateUser',
                request_serializer=auth__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=auth__pb2.CreateUserResponse.FromString,
                _registered_method=True)
        self.UpdateUser = channel.unary_unary(
                '/auth.AuthService/UpdateUser',
                request_serializer=auth__pb2.UpdateUserRequest.SerializeToString,
                response_deserializer=auth__pb2.UpdateUserResponse.FromString,
                _registered_method=True)
        self.DeleteUser = channel.unary_unary(
                '/auth.AuthService/DeleteUser',
                request_serializer=auth__pb2.DeleteUserRequest.SerializeToString,
                response_deserializer=auth__pb2.DeleteUserResponse.FromString,
                _registered_method=True)
        self.ActivateUser = channel.unary_unary(
                '/auth.AuthService/ActivateUser',
                request_serializer=auth__pb2.ActivateUserRequest.SerializeToString,
                response_deserializer=auth__pb2.ActivateUserResponse.FromString,
                _registered_method=True)
        self.DeactivateUser = channel.unary_unary(
                '/auth.AuthService/DeactivateUser',
                request_serializer=auth__pb2.DeactivateUserRequest.SerializeToString,
                response_deserializer=auth__pb2.DeactivateUserResponse.FromString,
                _registered_method=True)
        self.VerifyUser = channel.unary_unary(
                '/auth.AuthService/VerifyUser',
                request_serializer=auth__pb2.VerifyUserRequest.SerializeToString,
                response_deserializer=auth__pb2.VerifyUserResponse.FromString,
                _registered_method=True)
        self.ChangePassword = channel.unary_unary(
                '/auth.AuthService/ChangePassword',
                request_serializer=auth__pb2.ChangePasswordRequest.SerializeToString,
                response_deserializer=auth__pb2.ChangePasswordResponse.FromString,
                _registered_method=True)
        self.ListRoles = channel.unary_unary(
                '/auth.AuthService/ListRoles',
                request_serializer=auth__pb2.ListRolesRequest.SerializeToString,
                response_deserializer=auth__pb2.ListRolesResponse.FromString,
                _registered_method=True)
        self.CreateRole = channel.unary_unary(
                '/auth.AuthService/CreateRole',
                request_serializer=auth__pb2.CreateRoleRequest.SerializeToString,
                response_deserializer=auth__pb2.CreateRoleResponse.FromString,
                _registered_method=True)
        self.UpdateRole = channel.unary_unary(
                '/auth.AuthService/UpdateRole',
                request_serializer=auth__pb2.UpdateRoleRequest.SerializeToString,
                response_deserializer=auth__pb2.UpdateRoleResponse.FromString,
                _registered_method=True)
        self.DeleteRole = channel.unary_unary(
                '/auth.AuthService/DeleteRole',
                request_serializer=auth__pb2.DeleteRoleRequest.SerializeToString,
                response_deserializer=auth__pb2.DeleteRoleResponse.FromString,
                _registered_method=True)
        self.AssignUserRole = channel.unary_unary(
                '/auth.AuthService/AssignUserRole',
                request_serializer=auth__pb2.AssignUserRoleRequest.SerializeToString,
                response_deserializer=auth__pb2.AssignUserRoleResponse.FromString,
                _registered_method=True)
        self.RevokeUserRole = channel.unary_unary(
                '/auth.AuthService/RevokeUserRole',
                request_serializer=auth__pb2.RevokeUserRoleRequest.SerializeToString,
                response_deserializer=auth__pb2.RevokeUserRoleResponse.FromString,
                _registered_method=True)
        self.ListPermissions = channel.unary_unary(
                '/auth.AuthService/ListPermissions',
                request_serializer=auth__pb2.ListPermissionsRequest.SerializeToString,
                response_deserializer=auth__pb2.ListPermissionsResponse.FromString,
                _registered_method=True)
        self.AssignPermissions = channel.unary_unary(
                '/auth.AuthService/AssignPermissions',
                request_serializer=auth__pb2.AssignPermissionsRequest.SerializeToString,
                response_deserializer=auth__pb2.AssignPermissionsResponse.FromString,
                _registered_method=True)
        self.CheckPermission = channel.unary_unary(
                '/auth.AuthService/CheckPermission',
                request_serializer=auth__pb2.CheckPermissionRequest.SerializeToString,
                response_deserializer=auth__pb2.CheckPermissionResponse.FromString,
                _registered_method=True)
        self.GetUserStats = channel.unary_unary(
                '/auth.AuthService/GetUserStats',
                request_serializer=auth__pb2.GetUserStatsRequest.SerializeToString,
                response_deserializer=auth__pb2.GetUserStatsResponse.FromString,
                _registered_method=True)
        self.GetSecurityStats = channel.unary_unary(
                '/auth.AuthService/GetSecurityStats',
                request_serializer=auth__pb2.GetSecurityStatsRequest.SerializeToString,
                response_deserializer=auth__pb2.GetSecurityStatsResponse.FromString,
                _registered_method=True)
        self.GetUserActivity = channel.unary_unary(
                '/auth.AuthService/GetUserActivity',
                request_serializer=auth__pb2.GetUserActivityRequest.SerializeToString,
                response_deserializer=auth__pb2.GetUserActivityResponse.FromString,
                _registered_method=True)
        self.CreateOrganization = channel.unary_unary(
                '/auth.AuthService/CreateOrganization',
                request_serializer=auth__pb2.CreateOrganizationRequest.SerializeToString,
                response_deserializer=auth__pb2.CreateOrganizationResponse.FromString,
                _registered_method=True)
        self.GetOrganization = channel.unary_unary(
                '/auth.AuthService/GetOrganization',
                request_serializer=auth__pb2.GetOrganizationRequest.SerializeToString,
                response_deserializer=auth__pb2.GetOrganizationResponse.FromString,
                _registered_method=True)
        self.ListOrganizations = channel.unary_unary(
                '/auth.AuthService/ListOrganizations',
                request_serializer=auth__pb2.ListOrganizationsRequest.SerializeToString,
                response_deserializer=auth__pb2.ListOrganizationsResponse.FromString,
                _registered_method=True)
        self.GetOrganizationStats = channel.unary_unary(
                '/auth.AuthService/GetOrganizationStats',
                request_serializer=auth__pb2.GetOrganizationStatsRequest.SerializeToString,
                response_deserializer=auth__pb2.GetOrganizationStatsResponse.FromString,
                _registered_method=True)
        self.BulkCreateUsers = channel.unary_unary(
                '/auth.AuthService/BulkCreateUsers',
                request_serializer=auth__pb2.BulkCreateUsersRequest.SerializeToString,
                response_deserializer=auth__pb2.BulkCreateUsersResponse.FromString,
                _registered_method=True)
        self.BulkUpdateUsers = channel.unary_unary(
                '/auth.AuthService/BulkUpdateUsers',
                request_serializer=auth__pb2.BulkUpdateUsersRequest.SerializeToString,
                response_deserializer=auth__pb2.BulkUpdateUsersResponse.FromString,
                _registered_method=True)
        self.BulkDeleteUsers = channel.unary_unary(
                '/auth.AuthService/BulkDeleteUsers',
                request_serializer=auth__pb2.BulkDeleteUsersRequest.SerializeToString,
                response_deserializer=auth__pb2.BulkDeleteUsersResponse.FromString,
                _registered_method=True)
        self.BulkCheckPermissions = channel.unary_unary(
                '/auth.AuthService/BulkCheckPermissions',
                request_serializer=auth__pb2.BulkCheckPermissionsRequest.SerializeToString,
                response_deserializer=auth__pb2.BulkCheckPermissionsResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/auth.AuthService/HealthCheck',
                request_serializer=auth__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=auth__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class AuthServiceServicer(object):
    """Auth service definition
    """

    def Authenticate(self, request, context):
        """Authentication operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateToken(self, request, context):
        """Token operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUser(self, request, context):
        """User operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActivateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeactivateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangePassword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRoles(self, request, context):
        """Role operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateRole(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRole(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRole(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssignUserRole(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeUserRole(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPermissions(self, request, context):
        """Permission operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssignPermissions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckPermission(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserStats(self, request, context):
        """Statistics operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSecurityStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserActivity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateOrganization(self, request, context):
        """Organization operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrganization(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListOrganizations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrganizationStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BulkCreateUsers(self, request, context):
        """Bulk operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BulkUpdateUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BulkDeleteUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BulkCheckPermissions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Authenticate': grpc.unary_unary_rpc_method_handler(
                    servicer.Authenticate,
                    request_deserializer=auth__pb2.AuthenticateRequest.FromString,
                    response_serializer=auth__pb2.AuthenticateResponse.SerializeToString,
            ),
            'ValidateToken': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateToken,
                    request_deserializer=auth__pb2.ValidateTokenRequest.FromString,
                    response_serializer=auth__pb2.ValidateTokenResponse.SerializeToString,
            ),
            'RefreshToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshToken,
                    request_deserializer=auth__pb2.RefreshTokenRequest.FromString,
                    response_serializer=auth__pb2.RefreshTokenResponse.SerializeToString,
            ),
            'RevokeToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeToken,
                    request_deserializer=auth__pb2.RevokeTokenRequest.FromString,
                    response_serializer=auth__pb2.RevokeTokenResponse.SerializeToString,
            ),
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=auth__pb2.GetUserRequest.FromString,
                    response_serializer=auth__pb2.GetUserResponse.SerializeToString,
            ),
            'ListUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUsers,
                    request_deserializer=auth__pb2.ListUsersRequest.FromString,
                    response_serializer=auth__pb2.ListUsersResponse.SerializeToString,
            ),
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=auth__pb2.CreateUserRequest.FromString,
                    response_serializer=auth__pb2.CreateUserResponse.SerializeToString,
            ),
            'UpdateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUser,
                    request_deserializer=auth__pb2.UpdateUserRequest.FromString,
                    response_serializer=auth__pb2.UpdateUserResponse.SerializeToString,
            ),
            'DeleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUser,
                    request_deserializer=auth__pb2.DeleteUserRequest.FromString,
                    response_serializer=auth__pb2.DeleteUserResponse.SerializeToString,
            ),
            'ActivateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.ActivateUser,
                    request_deserializer=auth__pb2.ActivateUserRequest.FromString,
                    response_serializer=auth__pb2.ActivateUserResponse.SerializeToString,
            ),
            'DeactivateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeactivateUser,
                    request_deserializer=auth__pb2.DeactivateUserRequest.FromString,
                    response_serializer=auth__pb2.DeactivateUserResponse.SerializeToString,
            ),
            'VerifyUser': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyUser,
                    request_deserializer=auth__pb2.VerifyUserRequest.FromString,
                    response_serializer=auth__pb2.VerifyUserResponse.SerializeToString,
            ),
            'ChangePassword': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangePassword,
                    request_deserializer=auth__pb2.ChangePasswordRequest.FromString,
                    response_serializer=auth__pb2.ChangePasswordResponse.SerializeToString,
            ),
            'ListRoles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRoles,
                    request_deserializer=auth__pb2.ListRolesRequest.FromString,
                    response_serializer=auth__pb2.ListRolesResponse.SerializeToString,
            ),
            'CreateRole': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRole,
                    request_deserializer=auth__pb2.CreateRoleRequest.FromString,
                    response_serializer=auth__pb2.CreateRoleResponse.SerializeToString,
            ),
            'UpdateRole': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRole,
                    request_deserializer=auth__pb2.UpdateRoleRequest.FromString,
                    response_serializer=auth__pb2.UpdateRoleResponse.SerializeToString,
            ),
            'DeleteRole': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRole,
                    request_deserializer=auth__pb2.DeleteRoleRequest.FromString,
                    response_serializer=auth__pb2.DeleteRoleResponse.SerializeToString,
            ),
            'AssignUserRole': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignUserRole,
                    request_deserializer=auth__pb2.AssignUserRoleRequest.FromString,
                    response_serializer=auth__pb2.AssignUserRoleResponse.SerializeToString,
            ),
            'RevokeUserRole': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeUserRole,
                    request_deserializer=auth__pb2.RevokeUserRoleRequest.FromString,
                    response_serializer=auth__pb2.RevokeUserRoleResponse.SerializeToString,
            ),
            'ListPermissions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPermissions,
                    request_deserializer=auth__pb2.ListPermissionsRequest.FromString,
                    response_serializer=auth__pb2.ListPermissionsResponse.SerializeToString,
            ),
            'AssignPermissions': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignPermissions,
                    request_deserializer=auth__pb2.AssignPermissionsRequest.FromString,
                    response_serializer=auth__pb2.AssignPermissionsResponse.SerializeToString,
            ),
            'CheckPermission': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckPermission,
                    request_deserializer=auth__pb2.CheckPermissionRequest.FromString,
                    response_serializer=auth__pb2.CheckPermissionResponse.SerializeToString,
            ),
            'GetUserStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserStats,
                    request_deserializer=auth__pb2.GetUserStatsRequest.FromString,
                    response_serializer=auth__pb2.GetUserStatsResponse.SerializeToString,
            ),
            'GetSecurityStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSecurityStats,
                    request_deserializer=auth__pb2.GetSecurityStatsRequest.FromString,
                    response_serializer=auth__pb2.GetSecurityStatsResponse.SerializeToString,
            ),
            'GetUserActivity': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserActivity,
                    request_deserializer=auth__pb2.GetUserActivityRequest.FromString,
                    response_serializer=auth__pb2.GetUserActivityResponse.SerializeToString,
            ),
            'CreateOrganization': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateOrganization,
                    request_deserializer=auth__pb2.CreateOrganizationRequest.FromString,
                    response_serializer=auth__pb2.CreateOrganizationResponse.SerializeToString,
            ),
            'GetOrganization': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrganization,
                    request_deserializer=auth__pb2.GetOrganizationRequest.FromString,
                    response_serializer=auth__pb2.GetOrganizationResponse.SerializeToString,
            ),
            'ListOrganizations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListOrganizations,
                    request_deserializer=auth__pb2.ListOrganizationsRequest.FromString,
                    response_serializer=auth__pb2.ListOrganizationsResponse.SerializeToString,
            ),
            'GetOrganizationStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrganizationStats,
                    request_deserializer=auth__pb2.GetOrganizationStatsRequest.FromString,
                    response_serializer=auth__pb2.GetOrganizationStatsResponse.SerializeToString,
            ),
            'BulkCreateUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.BulkCreateUsers,
                    request_deserializer=auth__pb2.BulkCreateUsersRequest.FromString,
                    response_serializer=auth__pb2.BulkCreateUsersResponse.SerializeToString,
            ),
            'BulkUpdateUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.BulkUpdateUsers,
                    request_deserializer=auth__pb2.BulkUpdateUsersRequest.FromString,
                    response_serializer=auth__pb2.BulkUpdateUsersResponse.SerializeToString,
            ),
            'BulkDeleteUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.BulkDeleteUsers,
                    request_deserializer=auth__pb2.BulkDeleteUsersRequest.FromString,
                    response_serializer=auth__pb2.BulkDeleteUsersResponse.SerializeToString,
            ),
            'BulkCheckPermissions': grpc.unary_unary_rpc_method_handler(
                    servicer.BulkCheckPermissions,
                    request_deserializer=auth__pb2.BulkCheckPermissionsRequest.FromString,
                    response_serializer=auth__pb2.BulkCheckPermissionsResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=auth__pb2.HealthCheckRequest.FromString,
                    response_serializer=auth__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'auth.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('auth.AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """Auth service definition
    """

    @staticmethod
    def Authenticate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/Authenticate',
            auth__pb2.AuthenticateRequest.SerializeToString,
            auth__pb2.AuthenticateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/ValidateToken',
            auth__pb2.ValidateTokenRequest.SerializeToString,
            auth__pb2.ValidateTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/RefreshToken',
            auth__pb2.RefreshTokenRequest.SerializeToString,
            auth__pb2.RefreshTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/RevokeToken',
            auth__pb2.RevokeTokenRequest.SerializeToString,
            auth__pb2.RevokeTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/GetUser',
            auth__pb2.GetUserRequest.SerializeToString,
            auth__pb2.GetUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/ListUsers',
            auth__pb2.ListUsersRequest.SerializeToString,
            auth__pb2.ListUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/CreateUser',
            auth__pb2.CreateUserRequest.SerializeToString,
            auth__pb2.CreateUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/UpdateUser',
            auth__pb2.UpdateUserRequest.SerializeToString,
            auth__pb2.UpdateUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/DeleteUser',
            auth__pb2.DeleteUserRequest.SerializeToString,
            auth__pb2.DeleteUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActivateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/ActivateUser',
            auth__pb2.ActivateUserRequest.SerializeToString,
            auth__pb2.ActivateUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeactivateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/DeactivateUser',
            auth__pb2.DeactivateUserRequest.SerializeToString,
            auth__pb2.DeactivateUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/VerifyUser',
            auth__pb2.VerifyUserRequest.SerializeToString,
            auth__pb2.VerifyUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChangePassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/ChangePassword',
            auth__pb2.ChangePasswordRequest.SerializeToString,
            auth__pb2.ChangePasswordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRoles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/ListRoles',
            auth__pb2.ListRolesRequest.SerializeToString,
            auth__pb2.ListRolesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/CreateRole',
            auth__pb2.CreateRoleRequest.SerializeToString,
            auth__pb2.CreateRoleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/UpdateRole',
            auth__pb2.UpdateRoleRequest.SerializeToString,
            auth__pb2.UpdateRoleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/DeleteRole',
            auth__pb2.DeleteRoleRequest.SerializeToString,
            auth__pb2.DeleteRoleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssignUserRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/AssignUserRole',
            auth__pb2.AssignUserRoleRequest.SerializeToString,
            auth__pb2.AssignUserRoleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeUserRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/RevokeUserRole',
            auth__pb2.RevokeUserRoleRequest.SerializeToString,
            auth__pb2.RevokeUserRoleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPermissions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/ListPermissions',
            auth__pb2.ListPermissionsRequest.SerializeToString,
            auth__pb2.ListPermissionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssignPermissions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/AssignPermissions',
            auth__pb2.AssignPermissionsRequest.SerializeToString,
            auth__pb2.AssignPermissionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckPermission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/CheckPermission',
            auth__pb2.CheckPermissionRequest.SerializeToString,
            auth__pb2.CheckPermissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/GetUserStats',
            auth__pb2.GetUserStatsRequest.SerializeToString,
            auth__pb2.GetUserStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSecurityStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/GetSecurityStats',
            auth__pb2.GetSecurityStatsRequest.SerializeToString,
            auth__pb2.GetSecurityStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserActivity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/GetUserActivity',
            auth__pb2.GetUserActivityRequest.SerializeToString,
            auth__pb2.GetUserActivityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateOrganization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/CreateOrganization',
            auth__pb2.CreateOrganizationRequest.SerializeToString,
            auth__pb2.CreateOrganizationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrganization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/GetOrganization',
            auth__pb2.GetOrganizationRequest.SerializeToString,
            auth__pb2.GetOrganizationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListOrganizations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/ListOrganizations',
            auth__pb2.ListOrganizationsRequest.SerializeToString,
            auth__pb2.ListOrganizationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrganizationStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/GetOrganizationStats',
            auth__pb2.GetOrganizationStatsRequest.SerializeToString,
            auth__pb2.GetOrganizationStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BulkCreateUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/BulkCreateUsers',
            auth__pb2.BulkCreateUsersRequest.SerializeToString,
            auth__pb2.BulkCreateUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BulkUpdateUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/BulkUpdateUsers',
            auth__pb2.BulkUpdateUsersRequest.SerializeToString,
            auth__pb2.BulkUpdateUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BulkDeleteUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/BulkDeleteUsers',
            auth__pb2.BulkDeleteUsersRequest.SerializeToString,
            auth__pb2.BulkDeleteUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BulkCheckPermissions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/BulkCheckPermissions',
            auth__pb2.BulkCheckPermissionsRequest.SerializeToString,
            auth__pb2.BulkCheckPermissionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/HealthCheck',
            auth__pb2.HealthCheckRequest.SerializeToString,
            auth__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
